version: "3.9"

services:
  db:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: purple
      POSTGRES_PASSWORD: purple
      POSTGRES_DB: purple
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localai:
    image: ollama/ollama:latest
    container_name: local_ai_model
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      sh -c "ollama pull deepseek-llm:7b && ollama serve"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_service
    depends_on:
      - db
      - localai
    environment:
      DATABASE_URL: postgresql://purple:purple@db:5432/purple
      OLLAMA_API_URL: http://localai:11434
    ports:
      - "8000:8000"
    volumes:
      - ./prompt_gen:/app/prompt_gen

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_service
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  ollama_models:

